
spring:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
      
